version: '2'
services:
  rabbit:
    image: rabbitmq:3-management
    extends:
      file: config.yml
      service: base
    hostname: zimfarm
    restart: always
    logging:
      driver: none
    volumes:
      - ./docker_data/rabbitmq:/var/lib/rabbitmq
    ports:
      # communication with celery on workers
      - 28001:5672
  mongo:
    image: mongo:latest
    volumes:
      - ./docker_data/mongo:/data/db
    restart: always
    logging:
      driver: none
#  warehouse:
#    build:
#      context: ./warehouse
#      dockerfile: Dockerfile
#    extends:
#      file: config.yml
#      service: base
#    volumes:
#      - ZimFiles:/zimfiles
#    restart: always
#    ports:
#      # used by rsync to sync files back from workers
#      - 28002:27972

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    extends:
      file: config.yml
      service: base
    environment:
      - DEBUG=True
    links:
      - rabbit
      - mongo
    volumes:
      - ./backend/app:/app
      - /zimfarm:/mnt/zimfarm_output
    depends_on:
      - rabbit
      - mongo
    restart: always

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    links:
      - frontend
      - backend
    depends_on:
      - frontend
      - backend
    ports:
      - 28000:80
    restart: always

volumes:
  ZimFiles: