version: "2.2"

services:
  worker:
      build:
        context: ./celery
        dockerfile: Dockerfile
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
#        - /zimfarm:/ZimFileOutput
      environment:
        - USERNAME=admin
        - PASSWORD=admin_pass
        - HOST=farm.openzim.org
        - RABBITMQ_PORT=28001
        - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
        - OFFLINER_OUTPUT_PATH=/zimfarm
        - CPU_QUOTA=0.2
        - SHOW_COMMAND=True